### ISSUE TITLE
Support sub-directories

### ISSUE THREAD

**Issue by BigBlueHat** [progrium/viewdocs#35]
Currently, all links are prefixed with `http://<github-username>.viewdocs.io/<repository-name>`, but that prevents sub-directories from working (as they do on GitHub).

Example:
"What the HTTP is CouchApp?" on
http://couchapp.viewdocs.io/couchapp/couchapp-org/index.md
should link to
http://couchapp.viewdocs.io/couchapp/couchapp-org/what-is-couchapp.md
but actually links to
http://couchapp.viewdocs.io/couchapp/what-is-couchapp.md
which 404's.

The same content / paths work fine on GitHub's doc viewer:
https://github.com/couchapp/couchapp/blob/master/docs/couchapp-org/index.md

**Comment by josegonzalez** [comment]
I'm going to close this for now. It seems you've moved off to ReadTheDocs. If someone wants to provide a way to reproduce your setup, I'd be happy to take a look and implement the feature.
