### ISSUE TITLE
Site appears to be down 2015-01-13

### ISSUE THREAD

**Issue by calvingiles** [progrium/viewdocs#36]

**Comment by progrium** [comment]
You sure?

On Tue, Jan 13, 2015 at 4:49 AM, Calvin Giles <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/viewdocs/issues/36>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by calvingiles** [comment]
My apologies. I was unable to connect for about 5 minutes (from first time I tried onwards) but my connection was working fine. I wrote this then tried a bit later and it is indeed working again. Not sure where the issue was so probably ok to close this.

**Comment by josegonzalez** [comment]
This can probably be closed.
