### ISSUE TITLE
External HTTP connection issue

### ISSUE THREAD

**Issue by pixelbender** [progrium/viewdocs#41]
Seems other than 404 status codes leave unclosed resp.Body()
See:
https://github.com/progrium/viewdocs/blob/master/viewdocs.go#L115
https://github.com/progrium/viewdocs/blob/master/viewdocs.go#L215

**Comment by josegonzalez** [comment]
@pixelbender If you have a chance, mind poking at where the updated versions of these unclosed `resp.Body()` instances are?

**Comment by pixelbender** [comment]
@josegonzalez
https://github.com/progrium/viewdocs/blob/master/viewdocs.go#L238
https://github.com/progrium/viewdocs/blob/master/viewdocs.go#L149

**Comment by josegonzalez** [comment]
So just check for nil before we close it or...?

**Comment by pixelbender** [comment]
@josegonzalez sorry, the issue can be closed, here is the correct check now:
https://github.com/progrium/viewdocs/blob/master/viewdocs.go#L234-L236
