### ISSUE TITLE
Proposal: Federated viewdocs git Wiki enginge with gogs

### ISSUE THREAD

**Issue by almereyda** [progrium/viewdocs#43]
How could I theoretically misuse viewdocs to link to a private, but public gogs instance offering simple git editing for low end users?
In combination with viewdocs, we have a decoupled CMS.

What should I do?

**Comment by almereyda** [comment]
http://progrium.viewdocs.io/dokku/installation/ reads just too clean and simple not wanting to decouple it from GitHub. One could even borrow some ideas from https://github.com/claudioc/jingo @claudioc

**Comment by josegonzalez** [comment]
I think viewdocs should staying as is - that is to say, it should remain pretty simple and focused. 

If you'd like to provide editing features, that would perhaps be done within a custom template via some JS integration.
