### ISSUE TITLE
SSL is not supported

### ISSUE THREAD

**Issue by pawurb** [progrium/viewdocs#54]
https://viewdocs.io/ does not work.

Looks like the app is running on Heroku so adding a free certificate using https://letsencrypt.org/ should not be difficult https://devcenter.heroku.com/articles/automated-certificate-management

**Comment by josegonzalez** [comment]
We would also need SSL certificates for subdomains as that is where most of the docs are hosted.

I don't have DNS access so I'm unlikely to be able to build out any of this, unfortunately :(

**Comment by hugopeixoto** [comment]
Unfortunately, [Heroku does not support automated certificate management for applications with wildcard domains](https://devcenter.heroku.com/articles/automated-certificate-management#known-limitations).

Let's encrypt supports wildcard SSL certificates, but you'd have to host it somewhere else.

**Comment by josegonzalez** [comment]
Reopening. We're trying to figure out how to get the domain transferred to me (I can use Dokku opencollective funds for a wildcard cert) but we accidentally locked the domain for 60 days.

Once it goes through, we'll add a wildcard cert :)

**Comment by swrobel** [comment]
@josegonzalez I think you're past the 60 days now ... any luck?

**Comment by josegonzalez** [comment]
I checked in, something we'll get to when we have a chance.
